import {
  PERMISSIONS,
  STAFF_ROLES,
  USER_ROLES,
  type Permission,
  type UserRole,
} from "@/types/platform";

/** Default permissions per role. OWNER receives all permissions at runtime. */
export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  [USER_ROLES.OWNER]: Object.values(PERMISSIONS),
  [USER_ROLES.ADMIN]: [
    PERMISSIONS.CLIENTS_VIEW,
    PERMISSIONS.CLIENTS_EDIT,
    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.PROJECTS_EDIT,
    PERMISSIONS.PROJECTS_ASSIGN,
    PERMISSIONS.PAYMENTS_VIEW,
    PERMISSIONS.PAYMENTS_EDIT,
    PERMISSIONS.INVOICES_VIEW,
    PERMISSIONS.INVOICES_EDIT,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.SEO_VIEW,
    PERMISSIONS.SUPPORT_VIEW,
    PERMISSIONS.SUPPORT_RESPOND,
    PERMISSIONS.USERS_MANAGE,
    PERMISSIONS.SETTINGS_MANAGE,
    PERMISSIONS.LEADS_VIEW,
    PERMISSIONS.LEADS_EDIT,
    PERMISSIONS.PROPOSALS_VIEW,
    PERMISSIONS.PROPOSALS_EDIT,
    PERMISSIONS.CONTRACTS_VIEW,
    PERMISSIONS.CONTRACTS_EDIT,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.DOCUMENTS_VIEW,
    PERMISSIONS.DOCUMENTS_EDIT,
    PERMISSIONS.INTEGRATIONS_MANAGE,
  ],
  [USER_ROLES.PROJECT_MANAGER]: [
    PERMISSIONS.CLIENTS_VIEW,
    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.PROJECTS_EDIT,
    PERMISSIONS.PROJECTS_ASSIGN,
    PERMISSIONS.DOCUMENTS_VIEW,
    PERMISSIONS.SUPPORT_VIEW,
    PERMISSIONS.REPORTS_VIEW,
  ],
  [USER_ROLES.DEVELOPER]: [
    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.PROJECTS_EDIT,
    PERMISSIONS.DOCUMENTS_VIEW,
  ],
  [USER_ROLES.DESIGNER]: [
    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.PROJECTS_EDIT,
    PERMISSIONS.DOCUMENTS_VIEW,
  ],
  [USER_ROLES.SEO]: [
    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.SEO_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.ANALYTICS_VIEW,
  ],
  [USER_ROLES.ANALYTICS]: [
    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.REPORTS_VIEW,
  ],
  [USER_ROLES.SUPPORT]: [
    PERMISSIONS.CLIENTS_VIEW,
    PERMISSIONS.SUPPORT_VIEW,
    PERMISSIONS.SUPPORT_RESPOND,
    PERMISSIONS.PROJECTS_VIEW,
  ],
  [USER_ROLES.FINANCE]: [
    PERMISSIONS.PAYMENTS_VIEW,
    PERMISSIONS.PAYMENTS_EDIT,
    PERMISSIONS.INVOICES_VIEW,
    PERMISSIONS.INVOICES_EDIT,
    PERMISSIONS.CLIENTS_VIEW,
  ],
  [USER_ROLES.CLIENT]: [
    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.SUPPORT_VIEW,
    PERMISSIONS.INVOICES_VIEW,
    PERMISSIONS.PAYMENTS_VIEW,
    PERMISSIONS.DOCUMENTS_VIEW,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.SEO_VIEW,
    PERMISSIONS.REPORTS_VIEW,
  ],
};

export function isStaffRole(role: UserRole): boolean {
  return STAFF_ROLES.includes(role);
}

export function resolvePermissions(roles: UserRole[]): Permission[] {
  if (roles.includes(USER_ROLES.OWNER)) {
    return Object.values(PERMISSIONS);
  }

  const set = new Set<Permission>();
  for (const role of roles) {
    for (const permission of ROLE_PERMISSIONS[role] ?? []) {
      set.add(permission);
    }
  }
  return [...set];
}

export function hasPermission(
  permissions: Permission[],
  required: Permission,
): boolean {
  return permissions.includes(required);
}

export function hasAnyStaffRole(roles: UserRole[]): boolean {
  return roles.some(isStaffRole);
}
